input: tests/Testdata/Bike_Quality_Checker_Debug_File.ttl
output: test_results
add_datetime_to_output: False
write_results_to_excel: False
tests:
  - LooseConceptIdentifier
  # - SchemeCoherenceChecker
  # - SchemeIntegrityChecker
  - TopConceptIdentifier
  - SinglePrefLabelChecker