input: tests/Testdata/Bike_Quality_Checker_Debug_File.ttl
output: test/Testdata/Bike_Quality_Checker_Debug_File.xls
add_datetime_to_output_file: True
write_results_to_excel: True
logging: True
log_file: test/Testdata/SKOSQualityChecker.log
tests:
   - SinglePrefLabelChecker
   - SchemeCoherenceChecker
   - SchemeIntegrityChecker
   - SchemeIntegrityCheckerSPARQL
   - TopConceptIdentifier
   - IncompleteLanguageCoverageChecker
   - IncompleteLanguageCoverageCheckerSPARQL
   - LabelConflictChecker
   - OrphanConceptChecker
   - OrphanConceptCheckerSPARQL
   - OmittedTopConceptsChecker
   - SolelyTransitivelyRelatedConceptsChecker
   - SolelyTransitivelyRelatedConceptsCheckerSPARQL
   - TopConceptHavingBroaderConceptsChecker
   - TopConceptHavingBroaderConceptsCheckerSPARQL
   - CyclicHierarchicalRelationChecker
   - ValuelessAssociativeRelationsChecker
   - InvalidLanguageTagChecker
