input: /Users/joba/Downloads/datasets/geonames_ontology_v3.3_ext.ttl
#input: tests/Testdata/Bike_Quality_Checker_Debug_File.ttl
#input: /Users/joba/Downloads/eurovoc-skos-ap-eu.ttl
#input: /Users/joba/Downloads/datasets/agrovoc_2023-06-06_core.ttl
#input: /Users/joba/Downloads/datasets/eurovoc-skos-ap-eu.ttl
#output: /Users/joba/Downloads/test_results
output: data/test_results_geonames
add_datetime_to_output_file: True
write_results_to_excel: True
logging: True
log_file: /Users/joba/Downloads/SKOSQualityChecker.log
tests:
   # - SinglePrefLabelCheckerSPARQL
   - SinglePrefLabelChecker
   - LooseConceptIdentifierSPARQL
   - SchemeCoherenceCheckerSPARQL
   - SchemeIntegrityCheckerSPARQL
   - TopConceptIdentifierSPARQL
   #- IncompleteLanguageCoverageCheckerSPARQL
   - LabelConflictCheckerSPARQL
   - LabelConflictChecker
   - OrphanConceptIdentifierSPARQL
   - SolelyTransitivelyRelatedConceptsIdentifierSPARQL
   - TopConceptHavingBroaderConceptsCheckerSPARQL