#input: tests/Testdata/Bike_Quality_Checker_Debug_File.ttl
#input: tests/Testdata/EUROVOC.ttl
#input: /Users/joba/Downloads/agrovoc_2023-06-06_core.ttl
input: /Users/joba/Downloads/eurovoc-skos-ap-eu.ttl
#output: /Users/joba/Downloads/test_results
output: data/test_results
add_datetime_to_output: True
write_results_to_excel: True
tests:
   #- SinglePrefLabelCheckerSPARQL
   - SinglePrefLabelChecker
   #- LooseConceptIdentifierSPARQL
   #- SchemeCoherenceCheckerSPARQL
   #- SchemeIntegrityCheckerSPARQL
   #- TopConceptIdentifierSPARQL
   #- IncompleteLanguageCoverageCheckerSPARQL
   #- LabelConflictCheckerSPARQL
   #- OrphanConceptIdentifierSPARQL
   #- SolelyTransitivelyRelatedConceptsIdentifierSPARQL
   #- TopConceptHavingBroaderConceptsCheckerSPARQL